name: FragShop
main: com.github.fragsforfree.FragShop
version: 0.2.0
author: FragsForFree
commands:
  fragshop:
    description: easy commandline shop and item repair
    usage: /fragshop help
permissions:
  fragshop.repair:
    description: user can use the repair commands.
    default: op
  fragshop.shop:
    description: user can use the buy commands.
    default: op
  fragshop.admin:
    description: user can use admin commands.
    default: op